### ISSUE TITLE
Need Clear Instruction

### ISSUE THREAD

**Issue by amtra** [retoocs007/JavaSysMonitor#1]
Hi.. Its nice to add clear instruction how to build this JavaSysMonitor, since im new to linux stuffs. Or can provide prebuild JavaSysMonitor.war.

**Comment by retoocs007** [comment]
Hi, I have added GitHub workflow action to build war file on every release I create (not every commit).
You can see in the release v1.1.5 in the Assets that there is [JavaSysMonitor.war ](https://github.com/retoocs007/JavaSysMonitor/releases/tag/v1.1.5)

Btw, building Java applications are not only Linux bound. My development PC uses Windows OS. You can find plenty of instructions online how to build war packages from source files. Usually I'm using IntelliJ and Gradle task "build" to build war files.

**Comment by amtra** [comment]
I tried gradle and cant get it worked. btw thanks for the build.
